### ISSUE TITLE
Example 13...

### ISSUE THREAD

**Issue by gonsolo** [ingowald/optix7course#13]
Not exactly an issue but since you wrote
> Whichever of these - or other - features you might want to play around with: Let me know how it works out ... and have fun doing it,
and I didn't know how the best way to let you know.

I decided to take the course to learn the Optix API, but I did it the other way around; implement Optix (or a part of it) in Software step by step. It was fun even if the result is a bit, ahem, hacky. :) You can find my forked repository here: https://github.com/gonsolo/optix7course.

**Comment by ingowald** [comment]
Yes, agreed - that's a great way of learning how it works internally - I've done the same, too, actually :-).

Closing this, though, as I'm not sure it helps others to see this as a "issue". Have fun!
