### ISSUE TITLE
Denoising Seperate Channels - Normal and Albedo contain no data.

### ISSUE THREAD

**Issue by nreis011** [ingowald/optix7course#18]
As the title says, in the last tutorial, the Albedo and Normal channels appear to contain no data. Using this tutorial as a basis, I've been trying to get the Albedo and Normal maps from a given image, however, have been failing to do so. Upon digging around the code, it seems these two buffers are not fed any data.

**Comment by ingowald** [comment]
Oh; wow. I'm amazed that nobody found that, yet.... great catch!
Fixed; it was simply writing the values at the end of raygen - copy-pasta wrote color like prev sample, but didn't write the albedo or normal, even though it computed it :-/. 
Great find - thx!
