### ISSUE TITLE
longer memory

### ISSUE THREAD

**Issue by ED-97** [ingowald/optix7course#26]
Can I apply for a vector in Optix? I tried Thrust, but there was a problem during compilation

**Comment by ED-97** [comment]
and i use the cudamalloc also have error in pipelinelink,this is my problem or Compilation problems

**Comment by ingowald** [comment]
Hey - I'm not sure I understand the question/problem. Are you saying that the codebase does not compile? If so could you post some more info and/or actually error messages?

Also I have no idea what you mean with a "vector" in optix!? you mean a SIMD/SSE/AVX vector? or a std::vector!? or a mathematical vector!?

**Comment by ED-97** [comment]
here is the situation i want use the optix to render a scene and i need to get all fragment,This memory is of indeterminate length,and i need  save them in device memory(OIT), i think this is SIMD vector.
and i use the thrust::device_vector have this error: 
"COMPILE ERROR: Invalid PTX input: ptx2llvm-module-001: error: Failed to translate PTX input to LLVM,Virtual function calls are not supported in class "thrust2mr15memory_resourceINS_7pointerIvNS_8cuda_cub3tagENS_16tagged_referenceIvS4_EENS_11use_defaultEEEEE" (vtable symbol name: "_ZTVN6thrust2mr15memory_resourceINS_7pointerIvNS_8cuda_cub3tagENS_16tagged_referenceIvS4_EENS_11use_defaultEEEEE")."
i think this is optix not support my work,
do you have other way to solve my problem
i also try to cudamalloc  in raygenfunction but i get this error: 
exception: OPTIX_ERROR_PIPELINE_LINK_ERROR: Optix call 'optixPipelineCreate,I'm not sure if it's not working or if it's my fault,
Can you give me some guidance
