### ISSUE TITLE
Memory Leak in SampleRenderer When Loading a New Model?

### ISSUE THREAD

**Issue by pseudo-randomness** [ingowald/optix7course#36]
I'm modifying an app that uses the SampleRenderer class. I added the following function that replaces the current model with a new one. It works very well, but GPU memory increases each time I add new models until it eventually runs out of memory. _nvidia-smi_ shows memory increasing by 2 to 14 Mb depending on the complexity of the model.

```
  void SampleRenderer::setModel(Model *newModel)
  {
    model = newModel;
    createTextures();
    buildAccel();

    owlBuildPrograms(context);
    owlBuildPipeline(context);
    owlBuildSBT(context);
  }
```

**Comment by ingowald** [comment]
Would I be amiss to suspect that you posted this to the wrong github project? Though the "SampleRenderer" etc look close enough to this project to confuse me for a while the "owlXyz()" calls make me suspect this is supposed to be going to the OWL project github tracker? (https://github.com/owl-project/owl) ?

**Comment by pseudo-randomness** [comment]
You're probably right. I posted the issue to owl-project/owl
