### ISSUE TITLE
Errors in optix_device.h

### ISSUE THREAD

**Issue by TJaenichen** [ingowald/optix7course#6]

**Comment by ingowald** [comment]
Could you elaborate? I do not see what errors you might be seeing.

**Comment by TJaenichen** [comment]
Hi Ingo,

I tried to remove it as I had it fixed. It was some linking issue on my end, iirc.

Thanks though!

**Comment by ingowald** [comment]
ah, no prob :-). 
btw: if you're interested in the optix7couse, you may also want to have a look at the owl-project, and the owl version of that course sample: https://github.com/owl-project/owl
hf.
